import { useEffect, useState } from "react";
import { CheckCircle2, Wallet, PiggyBank, Search, Loader2, Download, ArrowRight, RotateCcw, ShieldCheck, Zap, CircleHelp } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { supabase } from "../../lib/supabaseClient";
import "./Transfers.css";
import PinModal from "../../components/PinModal/PinModal";

const iconByType = { checking: Wallet, savings: PiggyBank };
const quickAmounts = [25, 50, 100, 250];

function formatCurrency(amount) {
  return amount.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

function makeReceiptId() {
  return `HZ-${Date.now().toString(36).toUpperCase()}`;
}

function Transfers() {
  const { user } = useAuth();
  const [myAccounts, setMyAccounts] = useState([]);
  const [fromId, setFromId] = useState(null);
  const [toNumber, setToNumber] = useState("");
  const [recipient, setRecipient] = useState(null);
  const [lookupError, setLookupError] = useState("");
  const [lookupLoading, setLookupLoading] = useState(false);
  const [amount, setAmount] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const [success, setSuccess] = useState(null);
  const [showPinModal, setShowPinModal] = useState(false);
  const [pinConfigured, setPinConfigured] = useState(true);

  useEffect(() => {
    if (!user) return;
    const loadAccounts = supabase
      .from("accounts")
      .select("*")
      .eq("user_id", user.id)
      .then(({ data }) => {
        setMyAccounts(data || []);
        if (data?.length) setFromId(data[0].id);
      });
    const loadPin = supabase.rpc("has_transaction_pin");
    Promise.all([loadAccounts, loadPin]).then(([, { data }]) => setPinConfigured(!!data));
  }, [user]);

  const from = myAccounts.find((a) => a.id === fromId);

  const handleLookup = async () => {
    setRecipient(null);
    setLookupError("");
    if (toNumber.length < 4) return;
    setLookupLoading(true);
    const { data, error } = await supabase.rpc("lookup_account", { p_account_number: toNumber });
    setLookupLoading(false);
    if (error || !data || data.length === 0) {
      setLookupError("No account found with that number.");
      return;
    }
    if (from && toNumber === from.account_number) {
      setLookupError("You can't transfer to the same account.");
      return;
    }
    setRecipient(data[0]);
  };

const handleSubmit = (e) => {
  e.preventDefault();
  if (!recipient || !amount || !from) {
    setSubmitError("Choose a recipient and enter an amount to continue.");
    return;
  }
  if (Number(amount) <= 0) {
    setSubmitError("Enter an amount greater than $0.");
    return;
  }
  if (!pinConfigured) {
    setSubmitError("Set your 4-digit transaction PIN in Settings before sending money.");
    return;
  }
  setSubmitError("");
  setShowPinModal(true);
};

const executeTransfer = async () => {
  setShowPinModal(false);
  setSubmitting(true);
  setSubmitError("");

  const { error } = await supabase.rpc("transfer_funds", {
    p_from_account_id: from.id,
    p_to_account_number: toNumber,
    p_amount: Number(amount),
  });

  setSubmitting(false);

  if (error) {
    setSubmitError(error.message);
    return;
  }

  setSuccess({
    amount: Number(amount),
    recipientName: recipient.owner_name,
    recipientAccount: toNumber,
    fromAccount: from.account_number,
    fromName: from.name,
    receiptId: makeReceiptId(),
    createdAt: new Date(),
  });
};

  const downloadReceipt = () => {
    if (!success) return;
    const receipt = [
      "HORIZON — TRANSFER RECEIPT",
      "--------------------------------",
      `Receipt: ${success.receiptId}`,
      `Date: ${success.createdAt.toLocaleString()}`,
      "Status: Completed",
      "",
      `Amount: ${formatCurrency(success.amount)}`,
      `From: ${success.fromName} (${success.fromAccount})`,
      `To: ${success.recipientName} (${success.recipientAccount})`,
      "",
      "This receipt was generated by the Horizon application.",
    ].join("\n");
    const url = URL.createObjectURL(new Blob([receipt], { type: "text/plain" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = `${success.receiptId}-receipt.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setSuccess(null);
    setAmount("");
    setToNumber("");
    setRecipient(null);
    setLookupError("");
    // refresh balances
    supabase
      .from("accounts")
      .select("*")
      .eq("user_id", user.id)
      .then(({ data }) => setMyAccounts(data || []));
  };

  if (!from) return <div className="page-loading">Loading your accounts...</div>;

  return (
    <div className="page transfer-page">
      <div className="page__header">
        <div>
          <p className="page__eyebrow">Move money</p>
          <h1 className="page__title">Transfers</h1>
          <p className="transfer-page__subtitle">Send money securely and keep track of every move.</p>
        </div>
      </div>

      <div className="transfer-layout">
      <div className="transfer-card">
        {success ? (
          <div className="transfer-success">
            <div className="transfer-success__icon">
              <CheckCircle2 size={32} color="var(--positive-600)" />
            </div>
            <span className="transfer-success__eyebrow">Transfer complete</span>
            <h2 className="transfer-success__title">{formatCurrency(success.amount)} sent</h2>
            <p className="transfer-success__text">Your money is on its way to {success.recipientName}.</p>
            <div className="transfer-receipt">
              <div><span>From</span><strong>{success.fromName}</strong><small>•••• {String(success.fromAccount).slice(-4)}</small></div>
              <ArrowRight size={16} />
              <div><span>To</span><strong>{success.recipientName}</strong><small>•••• {String(success.recipientAccount).slice(-4)}</small></div>
            </div>
            <p className="transfer-success__meta">Receipt {success.receiptId} · {success.createdAt.toLocaleString()}</p>
            <div className="transfer-success__actions">
              <button className="transfer-btn transfer-btn--secondary" onClick={downloadReceipt}><Download size={15} /> Download receipt</button>
              <button className="transfer-btn" onClick={reset}><RotateCcw size={15} /> Make another transfer</button>
            </div>
          </div>
        ) : (
          <form onSubmit={handleSubmit}>
            <span className="transfer-account-group__label">From</span>
            <div className="transfer-account-group" style={{ marginBottom: 20 }}>
              {myAccounts.map((acc) => {
                const Icon = iconByType[acc.type] || Wallet;
                const selected = acc.id === fromId;
                return (
                  <button
                    type="button"
                    key={acc.id}
                    className={`account-option ${selected ? "account-option--selected" : ""}`}
                    onClick={() => setFromId(acc.id)}
                  >
                    <span className="account-option__icon"><Icon size={16} strokeWidth={1.75} /></span>
                    <span className="account-option__info">
                      <span className="account-option__name">{acc.name}</span>
                      <span className="account-option__number">•••• {acc.number}</span>
                    </span>
                    <span className="account-option__balance">{formatCurrency(acc.balance)}</span>
                  </button>
                );
              })}
            </div>

            <span className="transfer-account-group__label">To</span>
            <div className="recipient-lookup">
              <div className="recipient-lookup__input-wrap">
                <input
                  className="recipient-lookup__input"
                  placeholder="Enter 10-digit account number"
                  value={toNumber}
                  onChange={(e) => {
                    setToNumber(e.target.value.replace(/\D/g, "").slice(0, 10));
                    setRecipient(null);
                    setLookupError("");
                  }}
                  onBlur={handleLookup}
                  maxLength={10}
                />
                <button type="button" className="recipient-lookup__btn" onClick={handleLookup}>
                  {lookupLoading ? <Loader2 size={16} className="spin" /> : <Search size={16} />}
                </button>
              </div>

              {lookupError && <p className="transfer-error">{lookupError}</p>}

              {recipient && (
                <div className="recipient-found">
                  <span className="recipient-found__name">{recipient.owner_name}</span>
                  <span className="recipient-found__meta">{recipient.account_name}</span>
                </div>
              )}
            </div>

            <div className="transfer-amount-section">
              <span className="transfer-account-group__label">Amount</span>
              <div className="transfer-amount-wrap">
                <span className="transfer-amount-prefix">$</span>
                <input
                  type="number"
                  min="1"
                  step="0.01"
                  placeholder="0.00"
                  className="transfer-amount-input"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  required
                />
              </div>

              <div className="quick-amounts">
                {quickAmounts.map((val) => (
                  <button
                    type="button"
                    key={val}
                    className={`quick-amount ${Number(amount) === val ? "quick-amount--selected" : ""}`}
                    onClick={() => setAmount(String(val))}
                  >
                    ${val}
                  </button>
                ))}
              </div>
            </div>

            {submitError && <p className="transfer-error" role="alert">{submitError}</p>}

            <button
              type="submit"
              className="transfer-btn"
              disabled={!recipient || !amount || submitting}
            >
              {submitting ? "Sending..." : "Send transfer"}
            </button>
          </form>
        )}
      </div>
      <aside className="transfer-side-panel">
        <div className="transfer-side-panel__badge"><ShieldCheck size={16} /> Protected transfer</div>
        <h2>Move money with confidence.</h2>
        <p>Your transaction PIN and recipient confirmation help keep every transfer safe.</p>
        <div className="transfer-side-panel__items">
          <div><span><Zap size={15} /></span><p><strong>Fast and simple</strong><small>Send funds in just a few steps.</small></p></div>
          <div><span><ShieldCheck size={15} /></span><p><strong>PIN protected</strong><small>Every transfer needs your approval.</small></p></div>
          <div><span><CircleHelp size={15} /></span><p><strong>Need help?</strong><small>Visit Support for answers.</small></p></div>
        </div>
      </aside>
      </div>
      {showPinModal && (
  <PinModal
    title={`Confirm ${formatCurrency(Number(amount))} transfer`}
    description={`Send to ${recipient?.owner_name || "recipient"} ending in ${toNumber.slice(-4)}.`}
    onSuccess={executeTransfer}
    onCancel={() => setShowPinModal(false)}
  />
)}
    </div>
  );
}

export default Transfers;
